name: Upload Mods to Database

on:
  # 手动触发
  workflow_dispatch:

  # 每 24 小时触发一次（UTC 时间 0 点）
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC（北京时间 08:00）

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Upload mods to DB
        env:
          API_URL: ${{ secrets.API_URL }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          python .github/scripts/upload_mods_to_db.py
